services:
  rabbitmq:
    image: rabbitmq:4.2-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./.env
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq

  postgresql_info:
    image: postgres:18-alpine
    ports:
      - "5434:5432"
    env_file:
      - ./.env
    volumes:
      - ./postgresql/info:/var/lib/postgresql