spring.application.name=alerts
server.port=8091
spring.config.import=optional:file:.env[.properties]


#spring.rabbitmq.host=rabbitmqx
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_DEFAULT_USER}
spring.rabbitmq.password=${RABBITMQ_DEFAULT_PASS}
spring.cloud.stream.bindings.alertsSTW-out-0.destination=alerts
spring.cloud.stream.rabbit.bindings.alertsSTW-out-0.producer.routingKey=alertsUpdate


logging.file.name=logs/${spring.application.name}.log
logging.level.org.springframework.cloud.stream.binder.rabbit=INFO
