spring.application.name=alerts
server.port=8093
spring.config.import=optional:file:.env[.properties]


#spring.rabbitmq.host=rabbitmqx
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_DEFAULT_USER}
spring.rabbitmq.password=${RABBITMQ_DEFAULT_PASS}
spring.cloud.stream.bindings.alertsImage-out-0.destination=alert
spring.cloud.stream.rabbit.bindings.alertsImage-out-0.producer.routingKey=alertsWork
spring.cloud.stream.bindings.alertFunction-in-0.destination=alert
spring.cloud.stream.bindings.alertFunction-in-0.group=alert-handlers
spring.cloud.stream.rabbit.bindings.alertFunction-in-0.consumer.binding-routing-key=alertsChanged
spring.cloud.stream.rabbit.bindings.alertFunction-in-0.consumer.republish-to-dlq=true
spring.cloud.stream.rabbit.bindings.alertFunction-in-0.consumer.dead-letter-queue-name=missedEvents
spring.cloud.stream.rabbit.bindings.alertFunction-in-0.consumer.dead-letter-exchange=missedEvents


logging.file.name=logs/${spring.application.name}.log
logging.level.org.springframework.cloud.stream.binder.rabbit=INFO
