spring.application.name=epicAPI
server.port=8086
spring.config.import=optional:file:.env[.properties]

#spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_DEFAULT_USER}
spring.rabbitmq.password=${RABBITMQ_DEFAULT_PASS}
spring.cloud.stream.bindings.statusChange-out-0.destination=status
spring.cloud.stream.rabbit.bindings.statusChange-out-0.producer.routingKey=statusChanged
spring.cloud.stream.bindings.alertsChange-out-0.destination=alert
spring.cloud.stream.rabbit.bindings.alertsChange-out-0.producer.routingKey=alertsChanged


logging.file.name = logs/${spring.application.name}.log
logging.level.org.springframework.cloud.stream.binder.rabbit = INFO

#spring.data.redis.host=redis_epicapi
spring.data.redis.port=6381
spring.data.redis.password=${REDIS_HOST_PASSWORD_EPICAPI}