spring.application.name=info
server.port=8087
spring.config.import=optional:file:.env[.properties]

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_DEFAULT_USER}
spring.rabbitmq.password=${RABBITMQ_DEFAULT_PASS}
spring.cloud.stream.bindings.receiveChangeStatus-out-0.destination=telegram
spring.cloud.stream.rabbit.bindings.receiveChangeStatus-out-0.producer.routingKey=sendMessageFortnite
spring.cloud.stream.bindings.receiveChangeStatus-in-0.destination=status
spring.cloud.stream.bindings.receiveChangeStatus-in-0.group=status-handlers
spring.cloud.stream.rabbit.bindings.receiveChangeStatus-in-0.consumer.binding-routing-key=statusChanged
spring.cloud.stream.rabbit.bindings.receiveChangeStatus-in-0.consumer.republish-to-dlq=true
spring.cloud.stream.rabbit.bindings.receiveChangeStatus-in-0.consumer.dead-letter-queue-name=missedEvents
spring.cloud.stream.rabbit.bindings.receiveChangeStatus-in-0.consumer.dead-letter-exchange=missedEvents


logging.file.name = logs/${spring.application.name}.log
logging.level.org.springframework.cloud.stream.binder.rabbit = INFO

spring.datasource.username= ${POSTGRES_USER}
spring.datasource.password= ${POSTGRES_PASSWORD_INFO}
spring.datasource.url=jdbc:postgresql://localhost:5434/${POSTGRES_DB_INFO}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
springdoc.swagger-ui.enabled=true