spring.application.name=info
server.port=8087
spring.config.import=optional:file:.env[.properties]

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_DEFAULT_USER}
spring.rabbitmq.password=${RABBITMQ_DEFAULT_PASS}
spring.cloud.stream.bindings.statusChange-out-0.destination=status
spring.cloud.stream.rabbit.bindings.statusChange-out-0.producer.routingKey=statusChanged

logging.file.name = logs/${spring.application.name}.log
logging.level.org.springframework.cloud.stream.binder.rabbit = INFO