spring.application.name=image
server.port=8093
spring.config.import=optional:file:.env[.properties]

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_DEFAULT_USER}
spring.rabbitmq.password=${RABBITMQ_DEFAULT_PASS}

logging.file.name=logs/${spring.application.name}.log
logging.level.org.springframework.cloud.stream.binder.rabbit=INFO