spring.application.name=info
server.port=8089
spring.config.import=optional:file:.env[.properties]


spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_DEFAULT_USER}
spring.rabbitmq.password=${RABBITMQ_DEFAULT_PASS}

logging.file.name=logs/${spring.application.name}.log
logging.level.org.springframework.cloud.stream.binder.rabbit=INFO

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=${REDIS_HOST_PASSWORD_TG}