spring.application.name=tg
server.port=8089
spring.config.import=optional:file:.env[.properties]


spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_DEFAULT_USER}
spring.rabbitmq.password=${RABBITMQ_DEFAULT_PASS}
spring.cloud.stream.bindings.sendMessageFortnite-in-0.destination=telegram
spring.cloud.stream.bindings.sendMessageFortnite-in-0.group=telegram-handlers
spring.cloud.stream.rabbit.bindings.sendMessageFortnite-in-0.consumer.binding-routing-key=sendMessageFortnite
spring.cloud.stream.rabbit.bindings.sendMessageFortnite-in-0.consumer.republish-to-dlq=true
spring.cloud.stream.rabbit.bindings.sendMessageFortnite-in-0.consumer.dead-letter-queue-name=missedTGEvents
spring.cloud.stream.rabbit.bindings.sendMessageFortnite-in-0.consumer.dead-letter-exchange=missedEvents

logging.file.name=logs/${spring.application.name}.log
logging.level.org.springframework.cloud.stream.binder.rabbit=INFO

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=${REDIS_HOST_PASSWORD_TG}

springdoc.swagger-ui.enabled=true
